#!/bin/bash

rm -rf ../DemoReduceOut*
rm original.txt
rm subgraph.txt
rm testOutput.txt
rm *.class
rm recur/*.class
rm estimator/general/*.class
rm estimator/util/*.class
javac *.java
rm DemoReduce.jar
jar -cvfe DemoReduce.jar APLTester *.class recur/*.class estimator/general/*.class estimator/util/*.class
yarn jar DemoReduce.jar
